### ISSUE TITLE
NOTE TO SELF

### ISSUE THREAD

**Issue by banthebantz** [banthebantz/C-Plus-Plus-Learning#2]
# Get rid of the endl on every line. Flushing an output stream once per line is a very expensive operation. The output stream is buffered, characters are held in a large buffer in memory, and the buffer would be automatically flushed when it becomes full.

http://chris-sharpe.blogspot.co.uk/2016/02/why-you-shouldnt-use-stdendl.html

**Comment by Ragicil** [comment]
JEUS SUD CHRIST Y OUSTUPDS

**Comment by banthebantz** [comment]
![1513871196815s](https://user-images.githubusercontent.com/16517753/34500888-89d8bc58-f004-11e7-9ace-6885985f51fb.jpg)
